name: lean_scale_case
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #ROUTING
  auto_route: ^4.2.1

  #LOGIC
  stacked: ^2.3.13
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.3

  #UTILS
  cupertino_icons: ^1.0.2
  connectivity_plus: ^2.3.5
  http: ^0.13.4
  fluttertoast: ^8.0.9
  lottie: ^1.3.0
  path_provider: ^2.0.11
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^4.2.0
  build_runner: ^2.2.0
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
